name: CI pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]
        

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Build project
        run: go build -v ./...
      
      - name: Testing project
        run: go test ./...

      - name: Check code formatting 
        if: github.event_name == 'pull_request'
        run: |
          files=$(gofmt -s -l .)

          if [ -n "$files" ]; then
            echo "Code is NOT formatted"
            echo "$files"
            exit 1
          fi
      
      - name: Examines source code and report
        if: github.event_name == 'pull_request'
        run: go vet ./...
